"""full information model schema + pg_trgm

Revision ID: 31fdfa8031ac
Revises:
Create Date: 2026-06-27 13:41:07.969784

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31fdfa8031ac"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # pg_trgm powers the KB's fuzzy "similar past cases" GIN index (PLAN §4); must exist before it.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("build_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.Column("baseline_run_id", sa.Integer(), nullable=True),
        sa.Column("total_passed", sa.Integer(), nullable=False),
        sa.Column("total_failed", sa.Integer(), nullable=False),
        sa.Column("total_skipped", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["baseline_run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runs_build_number"), "runs", ["build_number"], unique=True)
    op.create_table(
        "test_identities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_name", sa.String(length=512), nullable=False),
        sa.Column("suite", sa.String(length=255), nullable=True),
        sa.Column("class_name", sa.String(length=255), nullable=True),
        sa.Column("method", sa.String(length=255), nullable=True),
        sa.Column("alias_of_id", sa.Integer(), nullable=True),
        sa.Column("alias_state", sa.String(length=16), nullable=False),
        sa.Column("owner_initials", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["alias_of_id"],
            ["test_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_test_identities_alias_of_id"), "test_identities", ["alias_of_id"], unique=False
    )
    op.create_index(
        op.f("ix_test_identities_canonical_name"),
        "test_identities",
        ["canonical_name"],
        unique=True,
    )
    op.create_table(
        "code_change_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("commit_id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.String(length=64), nullable=True),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paths", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_code_change_candidates_commit_id"),
        "code_change_candidates",
        ["commit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_code_change_candidates_run_id"), "code_change_candidates", ["run_id"], unique=False
    )
    op.create_table(
        "data_change_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("lx_table_code", sa.String(length=64), nullable=False),
        sa.Column("pk_lst", sa.String(length=255), nullable=True),
        sa.Column("change_type", sa.String(length=1), nullable=False),
        sa.Column("component_name", sa.String(length=128), nullable=True),
        sa.Column("author", sa.String(length=64), nullable=True),
        sa.Column("session_log_id", sa.String(length=64), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_change_candidates_changed_at"),
        "data_change_candidates",
        ["changed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_change_candidates_lx_table_code"),
        "data_change_candidates",
        ["lx_table_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_change_candidates_run_id"), "data_change_candidates", ["run_id"], unique=False
    )
    op.create_table(
        "failure_episodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_identity_id", sa.Integer(), nullable=False),
        sa.Column("episode_number", sa.Integer(), nullable=False),
        sa.Column("first_failure_run_id", sa.Integer(), nullable=False),
        sa.Column("first_failure_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_failing_run_id", sa.Integer(), nullable=True),
        sa.Column("last_failing_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fixed_in_run_id", sa.Integer(), nullable=True),
        sa.Column("fixed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("age_runs", sa.Integer(), nullable=False),
        sa.Column("triage_status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["first_failure_run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fixed_in_run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_failing_run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_identity_id"],
            ["test_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("test_identity_id", "episode_number", name="uq_episode_number"),
    )
    op.create_index(
        op.f("ix_failure_episodes_is_open"), "failure_episodes", ["is_open"], unique=False
    )
    op.create_index(
        op.f("ix_failure_episodes_test_identity_id"),
        "failure_episodes",
        ["test_identity_id"],
        unique=False,
    )
    op.create_table(
        "failure_signatures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_identity_id", sa.Integer(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("signature_hash", sa.String(length=64), nullable=False),
        sa.Column("exception_type", sa.String(length=255), nullable=True),
        sa.Column("first_seen_run_id", sa.Integer(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_run_id", sa.Integer(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["first_seen_run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_seen_run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_identity_id"],
            ["test_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_failure_signatures_normalized_text_trgm",
        "failure_signatures",
        ["normalized_text"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"normalized_text": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_failure_signatures_signature_hash"),
        "failure_signatures",
        ["signature_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_failure_signatures_test_identity_id"),
        "failure_signatures",
        ["test_identity_id"],
        unique=False,
    )
    op.create_table(
        "run_shards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("track", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "track", name="uq_run_shard_track"),
    )
    op.create_index(op.f("ix_run_shards_run_id"), "run_shards", ["run_id"], unique=False)
    op.create_table(
        "test_lifecycles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_identity_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("flaky", sa.Boolean(), nullable=False),
        sa.Column("reopen_count", sa.Integer(), nullable=False),
        sa.Column("acknowledged", sa.Boolean(), nullable=False),
        sa.Column("acknowledged_by", sa.String(length=128), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("all_time_first_failure_run_id", sa.Integer(), nullable=True),
        sa.Column("all_time_first_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failing_run_id", sa.Integer(), nullable=True),
        sa.Column("last_failing_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_episode_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["all_time_first_failure_run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_episode_id"],
            ["failure_episodes.id"],
            name="fk_lifecycle_current_episode",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["last_failing_run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_identity_id"],
            ["test_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_test_lifecycles_acknowledged"), "test_lifecycles", ["acknowledged"], unique=False
    )
    op.create_index(op.f("ix_test_lifecycles_flaky"), "test_lifecycles", ["flaky"], unique=False)
    op.create_index(op.f("ix_test_lifecycles_state"), "test_lifecycles", ["state"], unique=False)
    op.create_index(
        op.f("ix_test_lifecycles_test_identity_id"),
        "test_lifecycles",
        ["test_identity_id"],
        unique=True,
    )
    op.create_table(
        "attributions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.Column("causing_person", sa.String(length=128), nullable=True),
        sa.Column("reason_text", sa.Text(), nullable=True),
        sa.Column("cause_provenance", sa.String(length=16), nullable=False),
        sa.Column("reason_provenance", sa.String(length=16), nullable=False),
        sa.Column("original_ai_cause", sa.String(length=128), nullable=True),
        sa.Column("original_ai_reason", sa.Text(), nullable=True),
        sa.Column("validated_by", sa.String(length=128), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("entered_by", sa.String(length=128), nullable=True),
        sa.Column("signature_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["failure_episodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signature_id"],
            ["failure_signatures.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_attributions_episode_id"), "attributions", ["episode_id"], unique=True)
    op.create_index(
        op.f("ix_attributions_signature_id"), "attributions", ["signature_id"], unique=False
    )
    op.create_table(
        "classifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.Column("predicted_cause", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("suggested_contact", sa.String(length=128), nullable=True),
        sa.Column("llm_hypothesis", sa.Text(), nullable=True),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["failure_episodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_classifications_episode_id"), "classifications", ["episode_id"], unique=False
    )
    op.create_table(
        "test_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("test_identity_id", sa.Integer(), nullable=False),
        sa.Column("track", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=True),
        sa.Column("line", sa.Integer(), nullable=True),
        sa.Column("owner_initials", sa.String(length=32), nullable=True),
        sa.Column("error_type", sa.String(length=32), nullable=True),
        sa.Column("error_details", sa.Text(), nullable=True),
        sa.Column("error_stack_trace", sa.Text(), nullable=True),
        sa.Column("signature_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signature_id"],
            ["failure_signatures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_identity_id"],
            ["test_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "test_identity_id", "track", name="uq_run_test_track"),
    )
    op.create_index(op.f("ix_test_results_run_id"), "test_results", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_test_results_signature_id"), "test_results", ["signature_id"], unique=False
    )
    op.create_index(op.f("ix_test_results_status"), "test_results", ["status"], unique=False)
    op.create_index(
        op.f("ix_test_results_test_identity_id"), "test_results", ["test_identity_id"], unique=False
    )
    # ### end Alembic commands ###
    # Circular FK (test_lifecycles.current_episode_id -> failure_episodes.id): use_alter means it is
    # added after both tables exist, not inline in CREATE TABLE.
    op.create_foreign_key(
        "fk_lifecycle_current_episode",
        "test_lifecycles",
        "failure_episodes",
        ["current_episode_id"],
        ["id"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("fk_lifecycle_current_episode", "test_lifecycles", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_test_results_test_identity_id"), table_name="test_results")
    op.drop_index(op.f("ix_test_results_status"), table_name="test_results")
    op.drop_index(op.f("ix_test_results_signature_id"), table_name="test_results")
    op.drop_index(op.f("ix_test_results_run_id"), table_name="test_results")
    op.drop_table("test_results")
    op.drop_index(op.f("ix_classifications_episode_id"), table_name="classifications")
    op.drop_table("classifications")
    op.drop_index(op.f("ix_attributions_signature_id"), table_name="attributions")
    op.drop_index(op.f("ix_attributions_episode_id"), table_name="attributions")
    op.drop_table("attributions")
    op.drop_index(op.f("ix_test_lifecycles_test_identity_id"), table_name="test_lifecycles")
    op.drop_index(op.f("ix_test_lifecycles_state"), table_name="test_lifecycles")
    op.drop_index(op.f("ix_test_lifecycles_flaky"), table_name="test_lifecycles")
    op.drop_index(op.f("ix_test_lifecycles_acknowledged"), table_name="test_lifecycles")
    op.drop_table("test_lifecycles")
    op.drop_index(op.f("ix_run_shards_run_id"), table_name="run_shards")
    op.drop_table("run_shards")
    op.drop_index(op.f("ix_failure_signatures_test_identity_id"), table_name="failure_signatures")
    op.drop_index(op.f("ix_failure_signatures_signature_hash"), table_name="failure_signatures")
    op.drop_index(
        "ix_failure_signatures_normalized_text_trgm",
        table_name="failure_signatures",
        postgresql_using="gin",
        postgresql_ops={"normalized_text": "gin_trgm_ops"},
    )
    op.drop_table("failure_signatures")
    op.drop_index(op.f("ix_failure_episodes_test_identity_id"), table_name="failure_episodes")
    op.drop_index(op.f("ix_failure_episodes_is_open"), table_name="failure_episodes")
    op.drop_table("failure_episodes")
    op.drop_index(op.f("ix_data_change_candidates_run_id"), table_name="data_change_candidates")
    op.drop_index(
        op.f("ix_data_change_candidates_lx_table_code"), table_name="data_change_candidates"
    )
    op.drop_index(op.f("ix_data_change_candidates_changed_at"), table_name="data_change_candidates")
    op.drop_table("data_change_candidates")
    op.drop_index(op.f("ix_code_change_candidates_run_id"), table_name="code_change_candidates")
    op.drop_index(op.f("ix_code_change_candidates_commit_id"), table_name="code_change_candidates")
    op.drop_table("code_change_candidates")
    op.drop_index(op.f("ix_test_identities_canonical_name"), table_name="test_identities")
    op.drop_index(op.f("ix_test_identities_alias_of_id"), table_name="test_identities")
    op.drop_table("test_identities")
    op.drop_index(op.f("ix_runs_build_number"), table_name="runs")
    op.drop_table("runs")
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
